### ISSUE TITLE
RTMP support 

### ISSUE THREAD

**Issue by vishalkr058** [flowplayer/react-flowplayer#14]
Can we use this react-flowplayer for RTMP live streaming ?

**Comment by bbbo** [comment]
You cannot use rtmp in html5 video. It's a Flash-only protocol and Adobe stopped Flash support months ago.

**Comment by vishalkr058** [comment]
Okay, so, does this player support websocket url ?

**Comment by bbbo** [comment]
You need a https url to an MP4 file or HLS/DASH stream.
