### ISSUE TITLE
Hide all controls

### ISSUE THREAD

**Issue by klendi** [flowplayer/react-flowplayer#2]
Hello I can't seem to find a way to hide controls in flowplayer. I have tried disabling it by css. But still I can pause the video by clicking on it. And I saw there was a way to do it by passing ui prop but it doesn't seem to work.

`        controls={{ all: false }}
`
`.fp-ui {
  display: none;
}`

`        ui={2048}
`

I want to disable them all. Just use it as a background video. Is there a way to do that?

**Comment by bbbo** [comment]
Jut set the z-index of the player accordingly, as shown in https://flowplayer.com/demos/background-video

**Comment by klendi** [comment]
Yeah I checked that. And did the z-index but didn't work for me.

What I did I removed all the ui by css and then added `pointer-events: none` for fp-engine. Because video would pause on click.

Anyway thank you!
Closing this
