### ISSUE TITLE
Plugins not responding.

### ISSUE THREAD

**Issue by techscss** [flowplayer/react-flowplayer#21]
Hi,

I have been using FlowPlayer since month. I am now trying to add "Subtitles plugin" in ReactJS. Following is what I have done

    import React from 'react';
    import Qsel from '@flowplayer/player/plugins/qsel';
    import HLSPlugin from '@flowplayer/player/plugins/hls';
    import subtitles from '@flowplayer/player/plugins/subtitles';
    import '@flowplayer/player/flowplayer.css';
    import { useFlowplayer } from '@flowplayer/react-flowplayer';
    import flowplayer from '@flowplayer/player';
    
    flowplayer(HLSPlugin, Qsel, subtitles);
    const Player = () => {
        const { api: playerApi, Flowplayer } = useFlowplayer({
		token: xxxx,
	});
    return <>
        <Flowplayer
	    src='hls_link'
         />
     </>
    }

**FYI: Console shows no error.**

**Versions:**
React: ^17.0.1
@flowplayer/player  ^2.9.11,
@flowplayer/react-flowplayer  ^0.2.2

But Inspect Element shows the subtitle container

![Screenshot from 2022-02-22 16-04-29](https://user-images.githubusercontent.com/80825840/155112216-f55ae130-9dad-4dee-af80-bdce84eefce0.png)

**Comment by nnarhinen** [comment]
Hello!

I realise this is an old thread and most likely not relevant anymore, but if it still is relevant could you either share your HLS stream URL or link directly to the problematic setup?

Does your HLS contain embedded VTT subtitles or something similar?

Please reopen with the information if still relevant.
