### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by sgarchavada** [flowplayer/react-flowplayer#27]
I just try to implement this in my Next.js project.
Follow the basic steps from documentation,  and its crashing

```
import Flowplayer from "@flowplayer/react-flowplayer"
import "@flowplayer/player/flowplayer.css"

export const FlowVideoPlayer = ({src}) => {
   return (
     <Flowplayer token="my-token" src={src} />
   )
 }
 ```

**Comment by nnarhinen** [comment]
Hello!

You need to use a transpiler and/or bundler like Webpack + Babel to compile the JSX syntax and imports to plain javascript usable outside of modules.
