### ISSUE TITLE
Change qulity selection icon

### ISSUE THREAD

**Issue by den4ikr** [flowplayer/react-flowplayer#36]
Hi, is it possible to change quality selection icon? For example, i set quality to 360p, but quality selection icon is still HD.

**Comment by den4ikr** [comment]
???

**Comment by den4ikr** [comment]
????

**Comment by bbbo** [comment]
You cannot expect quick answers from a public repo. If the question is urgent, please contact support through the support link in your flowplayer.com account and explain your use case, we will then assign it to a developer.

**Comment by bbbo** [comment]
But generally: create a custom WebComponent and attach it to the player.
